from __future__ import annotations

from datetime import datetime, timezone
import json
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Depends, File, HTTPException, Request, Response, UploadFile, status
from sqlalchemy.orm import Session

from app.core.config import PROJECT_ROOT, get_settings
from app.core.security import (
    CSRF_COOKIE,
    SESSION_COOKIE,
    CurrentUser,
    create_csrf_token,
    create_session_token,
    get_current_user,
    require_csrf,
    require_roles,
    verify_password,
)
from app.db.database import get_db
from app.db.models import ApplicationEvent, InspectionRecord, User
from app.schemas import (
    GeocodeSearchResponse,
    GlobalPipelineGeoJSON,
    InspectionCreate,
    InspectionResponse,
    InspectionUpdate,
    LoginRequest,
    ManualPredictionRequest,
    PredictionResponse,
    ReplayRequest,
    UserResponse,
)
from app.services.artifacts import ArtifactService
from app.services.csv_validation import CsvValidationError, validate_csv_content
from app.services.geocoding import GeocodingService
from app.services.overpass import OverpassPipelineService


router = APIRouter(prefix="/api/v1")
settings = get_settings()
artifacts = ArtifactService()
geocoding_service = GeocodingService()
overpass_service = OverpassPipelineService()
DATA_DIR = PROJECT_ROOT / "data" / "demo"


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def model_unavailable() -> HTTPException:
    return HTTPException(
        status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
        detail={
            "code": "MODEL_NOT_AVAILABLE",
            "message": "An approved model is not available. Use Demo Mode or complete model training.",
        },
    )


def stamped_demo(kind: str) -> PredictionResponse:
    payload = artifacts.load_demo(kind)["response"]
    payload["prediction_timestamp"] = datetime.now(timezone.utc).isoformat()
    return PredictionResponse.model_validate(payload)


@router.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok", "application": "PipeGuard AI", "version": settings.app_version}


@router.get("/readiness")
def readiness() -> dict[str, Any]:
    return {
        "status": "ready" if artifacts.ready else "degraded",
        "api_ready": True,
        "database_configured": bool(settings.database_url),
        "model_ready": artifacts.ready,
        "model_error": artifacts.error,
        "demo_mode": settings.enable_demo_mode,
    }


@router.get("/version")
def version() -> dict[str, str]:
    return {"app_version": settings.app_version, "api_version": "v1", "schema_version": "1.0.0"}


@router.get("/model/info")
def model_info() -> dict[str, Any]:
    return artifacts.public_info()


@router.get("/model/metrics")
def model_metrics() -> dict[str, Any]:
    return load_json(PROJECT_ROOT / "model_artifacts" / "evaluation_metrics.json")


@router.get("/sensors")
def sensors() -> dict[str, Any]:
    return load_json(PROJECT_ROOT / "model_artifacts" / "sensor_inventory.json")


@router.get("/sensors/health")
def sensor_health() -> dict[str, Any]:
    return {
        "data_mode": "demo",
        "physical_sensors_connected": False,
        "availability_ratio": 0.986,
        "abnormal_sensors": ["n410", "p227"],
        "notice": "Replaying historical research readings as simulated live data.",
    }


@router.post("/predict/demo/normal", response_model=PredictionResponse)
def predict_demo_normal() -> PredictionResponse:
    if not settings.enable_demo_mode:
        raise HTTPException(status_code=404, detail="Demo mode is disabled")
    return stamped_demo("normal")


@router.post("/predict/demo/leak", response_model=PredictionResponse)
def predict_demo_leak() -> PredictionResponse:
    if not settings.enable_demo_mode:
        raise HTTPException(status_code=404, detail="Demo mode is disabled")
    return stamped_demo("leak")


@router.post("/predict/manual", response_model=PredictionResponse)
def predict_manual(payload: ManualPredictionRequest) -> PredictionResponse:
    if not artifacts.ready:
        raise model_unavailable()
    expected = [feature["name"] for feature in artifacts.schema["features"]]
    row = payload.model_dump()
    timestamp = row.pop("timestamp")
    vector = [[row[name] for name in expected]]
    probability = float(artifacts.model.predict_proba(vector)[0, 1])
    threshold = 0.5
    status_text = "Possible Leak" if probability >= threshold else "Normal"
    return PredictionResponse(
        status=status_text,
        leak_probability=probability,
        severity="High" if probability >= 0.8 else "Medium" if probability >= 0.5 else "Low",
        suspected_zone=None,
        abnormal_sensors=[],
        main_reason="Generated by the approved research model.",
        recommended_action=(
            "A technician should inspect the suspected zone."
            if status_text == "Possible Leak"
            else "Continue normal monitoring."
        ),
        data_mode="research",
        data_timestamp=timestamp,
        prediction_timestamp=datetime.now(timezone.utc),
        model_version=artifacts.manifest["model_version"],
        schema_version=artifacts.schema["schema_version"],
    )


@router.post("/predict/csv")
async def predict_csv(file: UploadFile = File(...)) -> dict[str, Any]:
    content = await file.read(settings.max_csv_bytes + 1)
    expected = [feature["name"] for feature in artifacts.schema["features"]]
    try:
        frame = validate_csv_content(content, file.content_type, expected)
    except (CsvValidationError, UnicodeDecodeError) as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    if not artifacts.ready:
        raise model_unavailable()
    probabilities = artifacts.model.predict_proba(frame[expected])[:, 1].tolist()
    return {
        "rows": len(frame),
        "predictions": [
            {
                "timestamp": timestamp.isoformat(),
                "leak_probability": float(probability),
                "status": "Possible Leak" if probability >= 0.5 else "Normal",
            }
            for timestamp, probability in zip(frame["Timestamp"], probabilities, strict=True)
        ],
    }


@router.post("/replay")
def replay(payload: ReplayRequest) -> dict[str, Any]:
    if not artifacts.ready:
        raise model_unavailable()
    results = [predict_manual(sample).model_dump(mode="json") for sample in payload.samples]
    return {"data_mode": "research", "results": results}


@router.get("/pipes")
def pipes(
    search: str | None = None,
    material: str | None = None,
    installation_year_min: int | None = None,
    installation_year_max: int | None = None,
    limit: int = 50,
    offset: int = 0,
) -> dict[str, Any]:
    records = load_json(DATA_DIR / "calgary_pipe_sample.json")
    if search:
        needle = search.lower()
        records = [
            row
            for row in records
            if needle in row["pipe_id"].lower() or needle in row["pressure_zone"].lower()
        ]
    if material:
        records = [row for row in records if row["material"].lower() == material.lower()]
    if installation_year_min is not None:
        records = [row for row in records if row["installation_year"] >= installation_year_min]
    if installation_year_max is not None:
        records = [row for row in records if row["installation_year"] <= installation_year_max]
    limit = max(1, min(limit, 100))
    return {
        "data_mode": "Research Data",
        "total": len(records),
        "items": records[offset : offset + limit],
        "notice": "Pipe age is calculated from the recorded installation year. It is not predicted by AI.",
    }


@router.get("/pipes/{pipe_id}")
def pipe_detail(pipe_id: str) -> dict[str, Any]:
    records = load_json(DATA_DIR / "calgary_pipe_sample.json")
    match = next((row for row in records if row["pipe_id"] == pipe_id), None)
    if not match:
        raise HTTPException(status_code=404, detail="Pipeline record not found")
    return match


@router.get("/pipes/{pipe_id}/history")
def pipe_history(pipe_id: str) -> dict[str, Any]:
    return {
        "pipe_id": pipe_id,
        "break_history": [],
        "inspection_history": [],
        "notice": "Historical breaks have not been spatially linked to this sample asset.",
    }


@router.get("/map/pipes")
def map_pipes() -> dict[str, Any]:
    return load_json(DATA_DIR / "calgary_pipe_sample.geojson")


@router.get("/map/communities")
def map_communities() -> dict[str, Any]:
    return {"type": "FeatureCollection", "features": [], "notice": "Use the offline geospatial preparation script to add simplified boundaries."}


@router.get("/inspection-priorities")
def inspection_priorities() -> dict[str, Any]:
    return {
        "data_mode": "Demo Data",
        "items": [
            {"zone": "Zone 4", "priority": "High", "reason": "Possible leak demonstration alert"},
            {"zone": "Zone 7", "priority": "Medium", "reason": "Pressure fluctuation demonstration alert"},
            {"zone": "Zone 2", "priority": "Low", "reason": "Routine inspection demonstration"},
        ],
    }


@router.get("/inspections", response_model=list[InspectionResponse])
def list_inspections(db: Session = Depends(get_db)) -> list[InspectionRecord]:
    return db.query(InspectionRecord).order_by(InspectionRecord.inspection_date.desc()).limit(100).all()


@router.get("/inspections/{inspection_id}", response_model=InspectionResponse)
def get_inspection(inspection_id: int, db: Session = Depends(get_db)) -> InspectionRecord:
    record = db.get(InspectionRecord, inspection_id)
    if not record:
        raise HTTPException(status_code=404, detail="Inspection record not found")
    return record


@router.post(
    "/inspections",
    response_model=InspectionResponse,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_csrf)],
)
def create_inspection(
    payload: InspectionCreate,
    request: Request,
    user: CurrentUser = Depends(require_roles("technician", "administrator")),
    db: Session = Depends(get_db),
) -> InspectionRecord:
    record = InspectionRecord(**payload.model_dump())
    record.technician = user.email
    db.add(record)
    db.add(
        ApplicationEvent(
            event_type="inspection_created",
            actor_user_id=user.id,
            request_id=request.state.request_id,
            summary=f"Inspection created for pipeline {payload.pipeline_id}",
        )
    )
    db.commit()
    db.refresh(record)
    return record


@router.patch(
    "/inspections/{inspection_id}",
    response_model=InspectionResponse,
    dependencies=[Depends(require_csrf)],
)
def update_inspection(
    inspection_id: int,
    payload: InspectionUpdate,
    request: Request,
    user: CurrentUser = Depends(require_roles("technician", "administrator")),
    db: Session = Depends(get_db),
) -> InspectionRecord:
    record = db.get(InspectionRecord, inspection_id)
    if not record:
        raise HTTPException(status_code=404, detail="Inspection record not found")
    for key, value in payload.model_dump(exclude_unset=True).items():
        setattr(record, key, value)
    record.updated_at = datetime.now(timezone.utc)
    db.add(
        ApplicationEvent(
            event_type="inspection_updated",
            actor_user_id=user.id,
            request_id=request.state.request_id,
            summary=f"Inspection {inspection_id} updated",
        )
    )
    db.commit()
    db.refresh(record)
    return record


@router.delete(
    "/inspections/{inspection_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_csrf)],
)
def delete_inspection(
    inspection_id: int,
    request: Request,
    user: CurrentUser = Depends(require_roles("administrator")),
    db: Session = Depends(get_db),
) -> Response:
    record = db.get(InspectionRecord, inspection_id)
    if not record:
        raise HTTPException(status_code=404, detail="Inspection record not found")
    db.delete(record)
    db.add(
        ApplicationEvent(
            event_type="inspection_deleted",
            actor_user_id=user.id,
            request_id=request.state.request_id,
            summary=f"Inspection {inspection_id} deleted",
        )
    )
    db.commit()
    return Response(status_code=204)


@router.post("/auth/login", response_model=UserResponse)
def login(payload: LoginRequest, response: Response, db: Session = Depends(get_db)) -> UserResponse:
    if not settings.enable_technician_login:
        raise HTTPException(status_code=404, detail="Login is disabled")
    user = db.query(User).filter(User.email == payload.email.lower()).first()
    if not user or not user.is_active or not verify_password(payload.password, user.password_hash):
        raise HTTPException(status_code=401, detail="Invalid email or password")
    session_token = create_session_token(user)
    csrf_token = create_csrf_token()
    secure = settings.app_env in {"production", "preview"}
    response.set_cookie(
        SESSION_COOKIE,
        session_token,
        httponly=True,
        secure=secure,
        samesite="lax",
        max_age=settings.access_session_minutes * 60,
        path="/",
    )
    response.set_cookie(
        CSRF_COOKIE,
        csrf_token,
        httponly=False,
        secure=secure,
        samesite="lax",
        max_age=settings.access_session_minutes * 60,
        path="/",
    )
    return UserResponse(id=user.id, email=user.email, role=user.role)


@router.post("/auth/logout", status_code=204, dependencies=[Depends(require_csrf)])
def logout(response: Response) -> Response:
    response.delete_cookie(SESSION_COOKIE, path="/")
    response.delete_cookie(CSRF_COOKIE, path="/")
    response.status_code = 204
    return response


@router.get("/auth/me", response_model=UserResponse)
def me(user: CurrentUser = Depends(get_current_user)) -> UserResponse:
    return UserResponse(id=user.id, email=user.email, role=user.role)


@router.get("/geocode/status")
def geocode_status() -> dict[str, Any]:
    return {
        "enabled": True,
        "provider": "Nominatim",
        "base_url_configured": bool(settings.geocoder_base_url),
        "user_agent_configured": bool(settings.geocoder_user_agent),
        "cache_enabled": True,
    }


@router.get("/geocode/search", response_model=GeocodeSearchResponse)
def geocode_search(q: str) -> GeocodeSearchResponse:
    if not q or not q.strip():
        raise HTTPException(status_code=422, detail="Search query must not be empty")
    return geocoding_service.search(q)


@router.get("/global-pipelines", response_model=GlobalPipelineGeoJSON)
def get_global_pipelines(
    south: float,
    west: float,
    north: float,
    east: float,
    substance: str = "water",
    limit: int = 1000,
) -> GlobalPipelineGeoJSON:
    try:
        return overpass_service.fetch_pipelines(
            south=south, west=west, north=north, east=east, substance=substance, limit=limit
        )
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

