import { z } from "zod";

export const PipelineAssetSchema = z.object({
  id: z.string(),
  name: z.string().optional(),
  pipe_id: z.string(),
  location: z.string(),
  zone: z.string(),
  latitude: z.number().min(-90).max(90),
  longitude: z.number().min(-180).max(180),
  installationYear: z.number().int().optional(),
  installation_year: z.number().int(),
  age: z.number().int().optional(),
  pipe_age: z.number().int(),
  material: z.enum(["Cast Iron", "Ductile Iron", "PVC", "Steel", "Polyethylene", "Concrete"]),
  diameterMm: z.number().positive().optional(),
  diameter_mm: z.number().positive(),
  lengthM: z.number().positive().optional(),
  length_m: z.number().positive(),
  capacity: z.number().positive().optional(),
  max_capacity_lps: z.number().positive(),
  pressureBar: z.number().min(0).optional(),
  pressure_bar: z.number().min(0),
  flowRate: z.number().min(0).optional(),
  flow_rate_lps: z.number().min(0),
  temperatureC: z.number().optional(),
  temperature_c: z.number(),
  operationalStatus: z.enum(["normal", "warning", "critical", "maintenance"]).optional(),
  operational_status: z.enum(["Active", "Maintenance Required", "Under Repair", "Inactive"]),
  inspectionStatus: z.enum(["not_required", "inspection_required", "under_review", "resolved", "passed", "failed"]).optional(),
  inspection_status: z.enum(["Passed", "Scheduled", "Pending Review", "Failed - Action Required"]),
  riskScore: z.number().min(0).max(100).optional(),
  risk_score: z.number().min(0).max(100),
  riskLevel: z.string().optional(),
  risk_level: z.enum(["Low", "Medium", "High", "Critical"]),
  lastInspectionDate: z.string().optional(),
  last_inspection_date: z.string(),
  recentPressureDropBar: z.number().optional(),
  recentFlowVariationLs: z.number().optional(),
  isDemoData: z.boolean().optional()
});

export type PipelineAsset = z.infer<typeof PipelineAssetSchema>;

export const PIPELINE_ASSETS_50: PipelineAsset[] = [
  // 24 Normal (Low Risk)
  {
    id: "PIPE-CAL-1002",
    pipe_id: "PIPE-CAL-1002",
    location: "Bow Trail & Crowchild Trail SW, Calgary",
    zone: "BROADCAST HILL",
    latitude: 51.0421,
    longitude: -114.1284,
    installation_year: 1995,
    pipe_age: 31,
    material: "Ductile Iron",
    diameter_mm: 450,
    length_m: 512.0,
    max_capacity_lps: 650,
    pressure_bar: 4.8,
    flow_rate_lps: 410.2,
    temperature_c: 10.8,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 22,
    risk_level: "Low",
    last_inspection_date: "2026-03-10"
  },
  {
    id: "PIPE-CAL-1004",
    pipe_id: "PIPE-CAL-1004",
    location: "Sarcee Trail & 17th Ave SW, Calgary",
    zone: "WEST CALGARY",
    latitude: 51.0378,
    longitude: -114.1752,
    installation_year: 2004,
    pipe_age: 22,
    material: "PVC",
    diameter_mm: 250,
    length_m: 320.0,
    max_capacity_lps: 280,
    pressure_bar: 5.1,
    flow_rate_lps: 195.5,
    temperature_c: 9.9,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 14,
    risk_level: "Low",
    last_inspection_date: "2026-05-18"
  },
  {
    id: "PIPE-CAL-1007",
    pipe_id: "PIPE-CAL-1007",
    location: "Shaganappi Trail & 40th Ave NW, Calgary",
    zone: "NOSE HILL",
    latitude: 51.0891,
    longitude: -114.1522,
    installation_year: 1999,
    pipe_age: 27,
    material: "PVC",
    diameter_mm: 200,
    length_m: 215.0,
    max_capacity_lps: 200,
    pressure_bar: 4.6,
    flow_rate_lps: 135.2,
    temperature_c: 10.2,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 18,
    risk_level: "Low",
    last_inspection_date: "2026-02-14"
  },
  {
    id: "PIPE-CAL-1008",
    pipe_id: "PIPE-CAL-1008",
    location: "Sunterra Blvd & 24th St SE, Calgary",
    zone: "MIDNAPORE",
    latitude: 50.9124,
    longitude: -114.0543,
    installation_year: 2011,
    pipe_age: 15,
    material: "Polyethylene",
    diameter_mm: 150,
    length_m: 140.0,
    max_capacity_lps: 130,
    pressure_bar: 5.4,
    flow_rate_lps: 88.0,
    temperature_c: 10.5,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 8,
    risk_level: "Low",
    last_inspection_date: "2026-04-20"
  },
  {
    id: "PIPE-CAL-1010",
    pipe_id: "PIPE-CAL-1010",
    location: "Beddington Trail & Country Hills Blvd NW",
    zone: "NOSE HILL",
    latitude: 51.1402,
    longitude: -114.0931,
    installation_year: 1991,
    pipe_age: 35,
    material: "Concrete",
    diameter_mm: 600,
    length_m: 850.0,
    max_capacity_lps: 1100,
    pressure_bar: 4.3,
    flow_rate_lps: 760.8,
    temperature_c: 9.8,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 25,
    risk_level: "Low",
    last_inspection_date: "2026-01-30"
  },
  {
    id: "PIPE-CAL-1012",
    pipe_id: "PIPE-CAL-1012",
    location: "Richmond Rd & 37th St SW, Calgary",
    zone: "BROADCAST HILL",
    latitude: 51.0254,
    longitude: -114.1411,
    installation_year: 2008,
    pipe_age: 18,
    material: "PVC",
    diameter_mm: 200,
    length_m: 290.0,
    max_capacity_lps: 220,
    pressure_bar: 5.2,
    flow_rate_lps: 140.5,
    temperature_c: 10.1,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 11,
    risk_level: "Low",
    last_inspection_date: "2026-06-12"
  },
  {
    id: "PIPE-CAL-1014",
    pipe_id: "PIPE-CAL-1014",
    location: "Southland Dr & 24th St SW, Calgary",
    zone: "GLENMORE",
    latitude: 50.9632,
    longitude: -114.1189,
    installation_year: 2001,
    pipe_age: 25,
    material: "Ductile Iron",
    diameter_mm: 300,
    length_m: 310.2,
    max_capacity_lps: 330,
    pressure_bar: 4.7,
    flow_rate_lps: 215.4,
    temperature_c: 10.9,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 19,
    risk_level: "Low",
    last_inspection_date: "2026-02-28"
  },
  {
    id: "PIPE-CAL-1017",
    pipe_id: "PIPE-CAL-1017",
    location: "Stoney Trail & 114th Ave SE, Calgary",
    zone: "OGDEN",
    latitude: 50.9498,
    longitude: -113.9521,
    installation_year: 2016,
    pipe_age: 10,
    material: "Polyethylene",
    diameter_mm: 250,
    length_m: 480.0,
    max_capacity_lps: 300,
    pressure_bar: 5.6,
    flow_rate_lps: 180.0,
    temperature_c: 9.5,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 5,
    risk_level: "Low",
    last_inspection_date: "2026-05-02"
  },
  {
    id: "PIPE-CAL-1018",
    pipe_id: "PIPE-CAL-1018",
    location: "University Dr & 24th Ave NW, Calgary",
    zone: "NOSE HILL",
    latitude: 51.0772,
    longitude: -114.1332,
    installation_year: 1993,
    pipe_age: 33,
    material: "Ductile Iron",
    diameter_mm: 350,
    length_m: 390.0,
    max_capacity_lps: 440,
    pressure_bar: 4.4,
    flow_rate_lps: 295.5,
    temperature_c: 10.7,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 21,
    risk_level: "Low",
    last_inspection_date: "2026-03-31"
  },
  {
    id: "PIPE-CAL-1020",
    pipe_id: "PIPE-CAL-1020",
    location: "Discovery Ridge Blvd & SR-8 SW, Calgary",
    zone: "WEST CALGARY",
    latitude: 51.0211,
    longitude: -114.2189,
    installation_year: 2009,
    pipe_age: 17,
    material: "PVC",
    diameter_mm: 250,
    length_m: 340.0,
    max_capacity_lps: 290,
    pressure_bar: 5.3,
    flow_rate_lps: 185.0,
    temperature_c: 9.7,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 9,
    risk_level: "Low",
    last_inspection_date: "2026-06-05"
  },
  {
    id: "PIPE-CAL-1023",
    pipe_id: "PIPE-CAL-1023",
    location: "Bowness Rd & 85th St NW, Calgary",
    zone: "BROADCAST HILL",
    latitude: 51.0855,
    longitude: -114.2052,
    installation_year: 1997,
    pipe_age: 29,
    material: "PVC",
    diameter_mm: 200,
    length_m: 305.0,
    max_capacity_lps: 210,
    pressure_bar: 4.9,
    flow_rate_lps: 138.0,
    temperature_c: 10.4,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 16,
    risk_level: "Low",
    last_inspection_date: "2026-04-11"
  },
  {
    id: "PIPE-CAL-1026",
    pipe_id: "PIPE-CAL-1026",
    location: "Crowchild Trail NW & 53rd St NW, Calgary",
    zone: "NOSE HILL",
    latitude: 51.1021,
    longitude: -114.1689,
    installation_year: 2006,
    pipe_age: 20,
    material: "PVC",
    diameter_mm: 300,
    length_m: 420.0,
    max_capacity_lps: 350,
    pressure_bar: 5.0,
    flow_rate_lps: 230.0,
    temperature_c: 10.0,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 12,
    risk_level: "Low",
    last_inspection_date: "2026-05-24"
  },
  {
    id: "PIPE-CAL-1028",
    pipe_id: "PIPE-CAL-1028",
    location: "16th Ave NW & 29th St NW, Calgary Foothills",
    zone: "NORTH HILL",
    latitude: 51.0678,
    longitude: -114.1255,
    installation_year: 1990,
    pipe_age: 36,
    material: "Ductile Iron",
    diameter_mm: 350,
    length_m: 380.0,
    max_capacity_lps: 410,
    pressure_bar: 4.5,
    flow_rate_lps: 270.0,
    temperature_c: 10.6,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 24,
    risk_level: "Low",
    last_inspection_date: "2026-02-09"
  },
  {
    id: "PIPE-CAL-1030",
    pipe_id: "PIPE-CAL-1030",
    location: "Stoney Trail & Country Hills Blvd NE",
    zone: "NORTH HILL",
    latitude: 51.1550,
    longitude: -113.9850,
    installation_year: 2018,
    pipe_age: 8,
    material: "Polyethylene",
    diameter_mm: 200,
    length_m: 520.0,
    max_capacity_lps: 230,
    pressure_bar: 5.7,
    flow_rate_lps: 145.0,
    temperature_c: 9.3,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 4,
    risk_level: "Low",
    last_inspection_date: "2026-07-10"
  },
  {
    id: "PIPE-CAL-1033",
    pipe_id: "PIPE-CAL-1033",
    location: "32nd Ave NE & 19th St NE, Calgary",
    zone: "NORTH HILL",
    latitude: 51.0821,
    longitude: -114.0112,
    installation_year: 2003,
    pipe_age: 23,
    material: "PVC",
    diameter_mm: 250,
    length_m: 350.0,
    max_capacity_lps: 290,
    pressure_bar: 4.8,
    flow_rate_lps: 190.0,
    temperature_c: 10.3,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 15,
    risk_level: "Low",
    last_inspection_date: "2026-03-22"
  },
  {
    id: "PIPE-CAL-1034",
    pipe_id: "PIPE-CAL-1034",
    location: "Shawnessy Blvd & Macleod Trail S, Calgary",
    zone: "MIDNAPORE",
    latitude: 50.8988,
    longitude: -114.0711,
    installation_year: 1998,
    pipe_age: 28,
    material: "Ductile Iron",
    diameter_mm: 350,
    length_m: 410.0,
    max_capacity_lps: 430,
    pressure_bar: 4.6,
    flow_rate_lps: 285.0,
    temperature_c: 10.8,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 20,
    risk_level: "Low",
    last_inspection_date: "2026-01-18"
  },
  {
    id: "PIPE-CAL-1036",
    pipe_id: "PIPE-CAL-1036",
    location: "64th Ave NE & Metis Trail NE, Calgary",
    zone: "NORTH HILL",
    latitude: 51.1102,
    longitude: -113.9550,
    installation_year: 2014,
    pipe_age: 12,
    material: "Polyethylene",
    diameter_mm: 300,
    length_m: 460.0,
    max_capacity_lps: 360,
    pressure_bar: 5.5,
    flow_rate_lps: 225.0,
    temperature_c: 9.6,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 7,
    risk_level: "Low",
    last_inspection_date: "2026-04-28"
  },
  {
    id: "PIPE-CAL-1037",
    pipe_id: "PIPE-CAL-1037",
    location: "Springbank Rd & 101st St SW, Calgary",
    zone: "WEST CALGARY",
    latitude: 51.0512,
    longitude: -114.2389,
    installation_year: 2005,
    pipe_age: 21,
    material: "PVC",
    diameter_mm: 250,
    length_m: 380.0,
    max_capacity_lps: 300,
    pressure_bar: 5.0,
    flow_rate_lps: 195.0,
    temperature_c: 10.2,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 13,
    risk_level: "Low",
    last_inspection_date: "2026-02-19"
  },
  {
    id: "PIPE-CAL-1040",
    pipe_id: "PIPE-CAL-1040",
    location: "McKenzie Towne Blvd & 130th Ave SE",
    zone: "MIDNAPORE",
    latitude: 50.9298,
    longitude: -113.9721,
    installation_year: 2002,
    pipe_age: 24,
    material: "PVC",
    diameter_mm: 300,
    length_m: 390.0,
    max_capacity_lps: 340,
    pressure_bar: 4.8,
    flow_rate_lps: 220.0,
    temperature_c: 10.5,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 17,
    risk_level: "Low",
    last_inspection_date: "2026-05-15"
  },
  {
    id: "PIPE-CAL-1043",
    pipe_id: "PIPE-CAL-1043",
    location: "14th St NW & 64th Ave NW, Huntington Hills",
    zone: "NOSE HILL",
    latitude: 51.1105,
    longitude: -114.0921,
    installation_year: 1994,
    pipe_age: 32,
    material: "Ductile Iron",
    diameter_mm: 300,
    length_m: 320.0,
    max_capacity_lps: 330,
    pressure_bar: 4.5,
    flow_rate_lps: 210.0,
    temperature_c: 10.3,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 22,
    risk_level: "Low",
    last_inspection_date: "2026-03-05"
  },
  {
    id: "PIPE-CAL-1044",
    pipe_id: "PIPE-CAL-1044",
    location: "Sun Valley Blvd & Chaparral Blvd SE",
    zone: "MIDNAPORE",
    latitude: 50.8850,
    longitude: -114.0411,
    installation_year: 2007,
    pipe_age: 19,
    material: "PVC",
    diameter_mm: 250,
    length_m: 360.0,
    max_capacity_lps: 280,
    pressure_bar: 5.1,
    flow_rate_lps: 175.0,
    temperature_c: 9.9,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 10,
    risk_level: "Low",
    last_inspection_date: "2026-06-21"
  },
  {
    id: "PIPE-CAL-1046",
    pipe_id: "PIPE-CAL-1046",
    location: "16th Ave NE & 68th St NE, Monterey Park",
    zone: "NORTH HILL",
    latitude: 51.0675,
    longitude: -113.9211,
    installation_year: 1996,
    pipe_age: 30,
    material: "PVC",
    diameter_mm: 300,
    length_m: 440.0,
    max_capacity_lps: 340,
    pressure_bar: 4.7,
    flow_rate_lps: 225.0,
    temperature_c: 10.5,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 18,
    risk_level: "Low",
    last_inspection_date: "2026-02-17"
  },
  {
    id: "PIPE-CAL-1048",
    pipe_id: "PIPE-CAL-1048",
    location: "Valley Ridge Blvd & Trans-Canada Hwy NW",
    zone: "BROADCAST HILL",
    latitude: 51.0895,
    longitude: -114.2750,
    installation_year: 2000,
    pipe_age: 26,
    material: "PVC",
    diameter_mm: 300,
    length_m: 480.0,
    max_capacity_lps: 370,
    pressure_bar: 4.9,
    flow_rate_lps: 240.0,
    temperature_c: 10.1,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 15,
    risk_level: "Low",
    last_inspection_date: "2026-04-05"
  },
  {
    id: "PIPE-CAL-1050",
    pipe_id: "PIPE-CAL-1050",
    location: "Copperfield Blvd & 130th Ave SE",
    zone: "MIDNAPORE",
    latitude: 50.9250,
    longitude: -113.9380,
    installation_year: 2012,
    pipe_age: 14,
    material: "Polyethylene",
    diameter_mm: 200,
    length_m: 310.0,
    max_capacity_lps: 210,
    pressure_bar: 5.4,
    flow_rate_lps: 130.0,
    temperature_c: 9.7,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 6,
    risk_level: "Low",
    last_inspection_date: "2026-06-18"
  },

  // 20 Warning (Medium / High Risk)
  {
    id: "PIPE-CAL-1003",
    pipe_id: "PIPE-CAL-1003",
    location: "Macleod Trail & 58th Ave SE, Calgary",
    zone: "GLENMORE",
    latitude: 51.0006,
    longitude: -114.0725,
    installation_year: 1965,
    pipe_age: 61,
    material: "Cast Iron",
    diameter_mm: 200,
    length_m: 180.2,
    max_capacity_lps: 210,
    pressure_bar: 2.7,
    flow_rate_lps: 142.0,
    temperature_c: 12.1,
    operational_status: "Maintenance Required",
    inspection_status: "Pending Review",
    risk_score: 76,
    risk_level: "High",
    last_inspection_date: "2025-09-22"
  },
  {
    id: "PIPE-CAL-1005",
    pipe_id: "PIPE-CAL-1005",
    location: "Center St N & 16th Ave N, Calgary",
    zone: "NORTH HILL",
    latitude: 51.0672,
    longitude: -114.0631,
    installation_year: 1982,
    pipe_age: 44,
    material: "Ductile Iron",
    diameter_mm: 350,
    length_m: 410.8,
    max_capacity_lps: 420,
    pressure_bar: 4.1,
    flow_rate_lps: 290.0,
    temperature_c: 11.5,
    operational_status: "Active",
    inspection_status: "Scheduled",
    risk_score: 42,
    risk_level: "Medium",
    last_inspection_date: "2025-06-04"
  },
  {
    id: "PIPE-CAL-1009",
    pipe_id: "PIPE-CAL-1009",
    location: "Heritage Dr & Blackfoot Trail SE, Calgary",
    zone: "GLENMORE",
    latitude: 50.9855,
    longitude: -114.0412,
    installation_year: 1988,
    pipe_age: 38,
    material: "Ductile Iron",
    diameter_mm: 300,
    length_m: 380.5,
    max_capacity_lps: 340,
    pressure_bar: 3.9,
    flow_rate_lps: 240.1,
    temperature_c: 11.8,
    operational_status: "Active",
    inspection_status: "Scheduled",
    risk_score: 35,
    risk_level: "Medium",
    last_inspection_date: "2025-10-11"
  },
  {
    id: "PIPE-CAL-1011",
    pipe_id: "PIPE-CAL-1011",
    location: "9th Ave & 4th St SE, Calgary Downtown",
    zone: "DOWNTOWN",
    latitude: 51.0441,
    longitude: -114.0556,
    installation_year: 1968,
    pipe_age: 58,
    material: "Cast Iron",
    diameter_mm: 250,
    length_m: 195.4,
    max_capacity_lps: 260,
    pressure_bar: 2.9,
    flow_rate_lps: 175.0,
    temperature_c: 12.5,
    operational_status: "Maintenance Required",
    inspection_status: "Failed - Action Required",
    risk_score: 82,
    risk_level: "High",
    last_inspection_date: "2025-12-01"
  },
  {
    id: "PIPE-CAL-1013",
    pipe_id: "PIPE-CAL-1013",
    location: "Barlow Trail & 16th Ave NE, Calgary",
    zone: "NORTH HILL",
    latitude: 51.0668,
    longitude: -113.9921,
    installation_year: 1975,
    pipe_age: 51,
    material: "Cast Iron",
    diameter_mm: 400,
    length_m: 540.0,
    max_capacity_lps: 520,
    pressure_bar: 3.1,
    flow_rate_lps: 385.0,
    temperature_c: 12.0,
    operational_status: "Maintenance Required",
    inspection_status: "Pending Review",
    risk_score: 79,
    risk_level: "High",
    last_inspection_date: "2025-08-19"
  },
  {
    id: "PIPE-CAL-1015",
    pipe_id: "PIPE-CAL-1015",
    location: "Fish Creek Provincial Park Crossing SE",
    zone: "MIDNAPORE",
    latitude: 50.9021,
    longitude: -114.0322,
    installation_year: 1985,
    pipe_age: 41,
    material: "Steel",
    diameter_mm: 500,
    length_m: 720.0,
    max_capacity_lps: 800,
    pressure_bar: 3.6,
    flow_rate_lps: 580.0,
    temperature_c: 11.3,
    operational_status: "Active",
    inspection_status: "Scheduled",
    risk_score: 48,
    risk_level: "Medium",
    last_inspection_date: "2025-11-05"
  },
  {
    id: "PIPE-CAL-1021",
    pipe_id: "PIPE-CAL-1021",
    location: "Memorial Dr & Edmonton Trail NE, Calgary",
    zone: "NORTH HILL",
    latitude: 51.0505,
    longitude: -114.0531,
    installation_year: 1980,
    pipe_age: 46,
    material: "Ductile Iron",
    diameter_mm: 300,
    length_m: 280.0,
    max_capacity_lps: 310,
    pressure_bar: 4.0,
    flow_rate_lps: 205.0,
    temperature_c: 11.4,
    operational_status: "Active",
    inspection_status: "Scheduled",
    risk_score: 38,
    risk_level: "Medium",
    last_inspection_date: "2025-07-14"
  },
  {
    id: "PIPE-CAL-1022",
    pipe_id: "PIPE-CAL-1022",
    location: "4th St SW & 12th Ave SW, Calgary Downtown",
    zone: "DOWNTOWN",
    latitude: 51.0418,
    longitude: -114.0712,
    installation_year: 1974,
    pipe_age: 52,
    material: "Cast Iron",
    diameter_mm: 250,
    length_m: 210.0,
    max_capacity_lps: 250,
    pressure_bar: 3.3,
    flow_rate_lps: 168.0,
    temperature_c: 12.2,
    operational_status: "Active",
    inspection_status: "Pending Review",
    risk_score: 64,
    risk_level: "High",
    last_inspection_date: "2025-10-29"
  },
  {
    id: "PIPE-CAL-1024",
    pipe_id: "PIPE-CAL-1024",
    location: "Canyon Meadows Dr & Bow Bottom Trail SE",
    zone: "MIDNAPORE",
    latitude: 50.9321,
    longitude: -114.0255,
    installation_year: 1986,
    pipe_age: 40,
    material: "Ductile Iron",
    diameter_mm: 400,
    length_m: 490.0,
    max_capacity_lps: 510,
    pressure_bar: 4.2,
    flow_rate_lps: 360.0,
    temperature_c: 11.1,
    operational_status: "Active",
    inspection_status: "Passed",
    risk_score: 30,
    risk_level: "Medium",
    last_inspection_date: "2025-11-28"
  },
  {
    id: "PIPE-CAL-1025",
    pipe_id: "PIPE-CAL-1025",
    location: "52nd St SE & 72nd Ave SE, Industrial Park",
    zone: "OGDEN",
    latitude: 50.9881,
    longitude: -113.9589,
    installation_year: 1979,
    pipe_age: 47,
    material: "Steel",
    diameter_mm: 450,
    length_m: 610.0,
    max_capacity_lps: 680,
    pressure_bar: 3.4,
    flow_rate_lps: 490.0,
    temperature_c: 12.6,
    operational_status: "Maintenance Required",
    inspection_status: "Failed - Action Required",
    risk_score: 85,
    risk_level: "High",
    last_inspection_date: "2026-01-15"
  },
  {
    id: "PIPE-CAL-1027",
    pipe_id: "PIPE-CAL-1027",
    location: "Elbow Dr & 75th Ave SW, Calgary",
    zone: "GLENMORE",
    latitude: 50.9862,
    longitude: -114.0841,
    installation_year: 1969,
    pipe_age: 57,
    material: "Cast Iron",
    diameter_mm: 200,
    length_m: 175.0,
    max_capacity_lps: 200,
    pressure_bar: 2.8,
    flow_rate_lps: 135.0,
    temperature_c: 12.4,
    operational_status: "Maintenance Required",
    inspection_status: "Pending Review",
    risk_score: 77,
    risk_level: "High",
    last_inspection_date: "2025-09-08"
  },
  {
    id: "PIPE-CAL-1031",
    pipe_id: "PIPE-CAL-1031",
    location: "10th Ave SW & 8th St SW, Beltline",
    zone: "DOWNTOWN",
    latitude: 51.0435,
    longitude: -114.0815,
    installation_year: 1984,
    pipe_age: 42,
    material: "Ductile Iron",
    diameter_mm: 250,
    length_m: 190.0,
    max_capacity_lps: 270,
    pressure_bar: 3.8,
    flow_rate_lps: 180.0,
    temperature_c: 11.6,
    operational_status: "Active",
    inspection_status: "Scheduled",
    risk_score: 45,
    risk_level: "Medium",
    last_inspection_date: "2025-08-01"
  },
  {
    id: "PIPE-CAL-1032",
    pipe_id: "PIPE-CAL-1032",
    location: "Glenmore Trail & 14th St SW, Calgary",
    zone: "GLENMORE",
    latitude: 50.9945,
    longitude: -114.0955,
    installation_year: 1976,
    pipe_age: 50,
    material: "Steel",
    diameter_mm: 600,
    length_m: 910.0,
    max_capacity_lps: 1200,
    pressure_bar: 3.7,
    flow_rate_lps: 890.0,
    temperature_c: 12.0,
    operational_status: "Active",
    inspection_status: "Pending Review",
    risk_score: 58,
    risk_level: "Medium",
    last_inspection_date: "2025-11-19"
  },
  {
    id: "PIPE-CAL-1035",
    pipe_id: "PIPE-CAL-1035",
    location: "Heritage Park Water Main Supply, Calgary",
    zone: "GLENMORE",
    latitude: 50.9812,
    longitude: -114.1011,
    installation_year: 1971,
    pipe_age: 55,
    material: "Cast Iron",
    diameter_mm: 200,
    length_m: 160.0,
    max_capacity_lps: 195,
    pressure_bar: 2.9,
    flow_rate_lps: 130.0,
    temperature_c: 12.7,
    operational_status: "Maintenance Required",
    inspection_status: "Failed - Action Required",
    risk_score: 81,
    risk_level: "High",
    last_inspection_date: "2025-10-04"
  },
  {
    id: "PIPE-CAL-1038",
    pipe_id: "PIPE-CAL-1038",
    location: "Peigan Trail & Barlow Trail SE, Calgary",
    zone: "OGDEN",
    latitude: 51.0188,
    longitude: -113.9989,
    installation_year: 1983,
    pipe_age: 43,
    material: "Ductile Iron",
    diameter_mm: 400,
    length_m: 520.0,
    max_capacity_lps: 550,
    pressure_bar: 3.9,
    flow_rate_lps: 390.0,
    temperature_c: 11.7,
    operational_status: "Active",
    inspection_status: "Scheduled",
    risk_score: 41,
    risk_level: "Medium",
    last_inspection_date: "2025-07-22"
  },
  {
    id: "PIPE-CAL-1039",
    pipe_id: "PIPE-CAL-1039",
    location: "4th St NW & 40th Ave NW, Highland Park",
    zone: "NORTH HILL",
    latitude: 51.0885,
    longitude: -114.0711,
    installation_year: 1977,
    pipe_age: 49,
    material: "Cast Iron",
    diameter_mm: 200,
    length_m: 185.0,
    max_capacity_lps: 205,
    pressure_bar: 3.0,
    flow_rate_lps: 140.0,
    temperature_c: 12.3,
    operational_status: "Maintenance Required",
    inspection_status: "Pending Review",
    risk_score: 73,
    risk_level: "High",
    last_inspection_date: "2025-12-14"
  },
  {
    id: "PIPE-CAL-1041",
    pipe_id: "PIPE-CAL-1041",
    location: "Edworthy Park Crossing, Bow River West",
    zone: "BROADCAST HILL",
    latitude: 51.0611,
    longitude: -114.1560,
    installation_year: 1987,
    pipe_age: 39,
    material: "Steel",
    diameter_mm: 450,
    length_m: 580.0,
    max_capacity_lps: 620,
    pressure_bar: 3.7,
    flow_rate_lps: 450.0,
    temperature_c: 11.0,
    operational_status: "Active",
    inspection_status: "Scheduled",
    risk_score: 39,
    risk_level: "Medium",
    last_inspection_date: "2025-09-30"
  },
  {
    id: "PIPE-CAL-1045",
    pipe_id: "PIPE-CAL-1045",
    location: "33rd Ave SW & 20th St SW, Marda Loop",
    zone: "WEST CALGARY",
    latitude: 51.0232,
    longitude: -114.1089,
    installation_year: 1979,
    pipe_age: 47,
    material: "Ductile Iron",
    diameter_mm: 200,
    length_m: 210.0,
    max_capacity_lps: 210,
    pressure_bar: 3.6,
    flow_rate_lps: 145.0,
    temperature_c: 11.9,
    operational_status: "Active",
    inspection_status: "Pending Review",
    risk_score: 52,
    risk_level: "Medium",
    last_inspection_date: "2025-11-11"
  },
  {
    id: "PIPE-CAL-1047",
    pipe_id: "PIPE-CAL-1047",
    location: "Fairmount Dr & 82nd Ave SE, Acadia",
    zone: "GLENMORE",
    latitude: 50.9798,
    longitude: -114.0589,
    installation_year: 1973,
    pipe_age: 53,
    material: "Cast Iron",
    diameter_mm: 250,
    length_m: 240.0,
    max_capacity_lps: 260,
    pressure_bar: 3.1,
    flow_rate_lps: 175.0,
    temperature_c: 12.1,
    operational_status: "Maintenance Required",
    inspection_status: "Failed - Action Required",
    risk_score: 84,
    risk_level: "High",
    last_inspection_date: "2025-10-18"
  },
  {
    id: "PIPE-CAL-1049",
    pipe_id: "PIPE-CAL-1049",
    location: "Heritage Meadows Rd & SE Main Feeder",
    zone: "GLENMORE",
    latitude: 50.9850,
    longitude: -114.0310,
    installation_year: 1989,
    pipe_age: 37,
    material: "Steel",
    diameter_mm: 500,
    length_m: 670.0,
    max_capacity_lps: 720,
    pressure_bar: 4.1,
    flow_rate_lps: 510.0,
    temperature_c: 11.2,
    operational_status: "Active",
    inspection_status: "Scheduled",
    risk_score: 33,
    risk_level: "Medium",
    last_inspection_date: "2025-08-25"
  },

  // 6 Critical Risk
  {
    id: "PIPE-CAL-1001",
    pipe_id: "PIPE-CAL-1001",
    location: "14th St & 8th Ave SW, Calgary",
    zone: "DOWNTOWN",
    latitude: 51.0458,
    longitude: -114.0892,
    installation_year: 1978,
    pipe_age: 48,
    material: "Cast Iron",
    diameter_mm: 300,
    length_m: 245.5,
    max_capacity_lps: 320,
    pressure_bar: 3.2,
    flow_rate_lps: 185.4,
    temperature_c: 11.2,
    operational_status: "Maintenance Required",
    inspection_status: "Failed - Action Required",
    risk_score: 88,
    risk_level: "Critical",
    last_inspection_date: "2025-11-14"
  },
  {
    id: "PIPE-CAL-1006",
    pipe_id: "PIPE-CAL-1006",
    location: "Ogden Rd & 50th Ave SE, Calgary",
    zone: "OGDEN",
    latitude: 50.9982,
    longitude: -114.0156,
    installation_year: 1972,
    pipe_age: 54,
    material: "Steel",
    diameter_mm: 500,
    length_m: 630.0,
    max_capacity_lps: 780,
    pressure_bar: 3.5,
    flow_rate_lps: 520.4,
    temperature_c: 13.0,
    operational_status: "Under Repair",
    inspection_status: "Failed - Action Required",
    risk_score: 92,
    risk_level: "Critical",
    last_inspection_date: "2026-07-02"
  },
  {
    id: "PIPE-CAL-1016",
    pipe_id: "PIPE-CAL-1016",
    location: "17th Ave SE & 36th St SE, Calgary",
    zone: "OGDEN",
    latitude: 51.0379,
    longitude: -113.9812,
    installation_year: 1970,
    pipe_age: 56,
    material: "Cast Iron",
    diameter_mm: 300,
    length_m: 260.0,
    max_capacity_lps: 310,
    pressure_bar: 2.8,
    flow_rate_lps: 210.0,
    temperature_c: 13.2,
    operational_status: "Under Repair",
    inspection_status: "Failed - Action Required",
    risk_score: 95,
    risk_level: "Critical",
    last_inspection_date: "2026-07-25"
  },
  {
    id: "PIPE-CAL-1019",
    pipe_id: "PIPE-CAL-1019",
    location: "Spiller Rd & 25th Ave SE, Calgary",
    zone: "DOWNTOWN",
    latitude: 51.0301,
    longitude: -114.0498,
    installation_year: 1963,
    pipe_age: 63,
    material: "Cast Iron",
    diameter_mm: 200,
    length_m: 165.0,
    max_capacity_lps: 190,
    pressure_bar: 2.6,
    flow_rate_lps: 130.0,
    temperature_c: 12.8,
    operational_status: "Maintenance Required",
    inspection_status: "Failed - Action Required",
    risk_score: 89,
    risk_level: "Critical",
    last_inspection_date: "2025-12-20"
  },
  {
    id: "PIPE-CAL-1029",
    pipe_id: "PIPE-CAL-1029",
    location: "1st St SE & 6th Ave SE, Calgary City Centre",
    zone: "DOWNTOWN",
    latitude: 51.0475,
    longitude: -114.0611,
    installation_year: 1960,
    pipe_age: 66,
    material: "Cast Iron",
    diameter_mm: 300,
    length_m: 230.0,
    max_capacity_lps: 300,
    pressure_bar: 2.5,
    flow_rate_lps: 195.0,
    temperature_c: 13.5,
    operational_status: "Inactive",
    inspection_status: "Failed - Action Required",
    risk_score: 97,
    risk_level: "Critical",
    last_inspection_date: "2026-06-30"
  },
  {
    id: "PIPE-CAL-1042",
    pipe_id: "PIPE-CAL-1042",
    location: "Kensington Rd & 10th St NW, Calgary",
    zone: "NORTH HILL",
    latitude: 51.0528,
    longitude: -114.0858,
    installation_year: 1967,
    pipe_age: 59,
    material: "Cast Iron",
    diameter_mm: 250,
    length_m: 170.0,
    max_capacity_lps: 240,
    pressure_bar: 2.7,
    flow_rate_lps: 160.0,
    temperature_c: 12.9,
    operational_status: "Under Repair",
    inspection_status: "Failed - Action Required",
    risk_score: 91,
    risk_level: "Critical",
    last_inspection_date: "2026-07-18"
  }
];

export function adapterToNormalizedPipelineAsset(raw: any): PipelineAsset {
  const pipe_id = raw.pipe_id || raw.pipeId || raw.id || "PIPE-UNKNOWN";
  const id = raw.id || pipe_id;
  const location = raw.location || "Calgary Network Segment";
  const zone = raw.zone || "DOWNTOWN";
  const latitude = typeof raw.latitude === "number" ? raw.latitude : 51.0447;
  const longitude = typeof raw.longitude === "number" ? raw.longitude : -114.0719;
  const installation_year = raw.installation_year || raw.installationYear || 1990;
  const pipe_age = raw.pipe_age || raw.age || (2026 - installation_year);
  const material = raw.material || "Cast Iron";
  const diameter_mm = raw.diameter_mm || raw.diameterMm || 300;
  const length_m = raw.length_m || raw.lengthM || 250.0;
  const max_capacity_lps = raw.max_capacity_lps || raw.capacity || 400;
  const pressure_bar = typeof raw.pressure_bar === "number" ? raw.pressure_bar : typeof raw.pressureBar === "number" ? raw.pressureBar : 4.2;
  const flow_rate_lps = typeof raw.flow_rate_lps === "number" ? raw.flow_rate_lps : typeof raw.flowRate === "number" ? raw.flowRate : 200;
  const temperature_c = typeof raw.temperature_c === "number" ? raw.temperature_c : typeof raw.temperatureC === "number" ? raw.temperatureC : 11.0;
  
  let risk_level: "Low" | "Medium" | "High" | "Critical" = raw.risk_level || raw.riskLevel || "Low";
  let risk_score = typeof raw.risk_score === "number" ? raw.risk_score : typeof raw.riskScore === "number" ? raw.riskScore : 20;

  if (raw.risk_level === "critical" || raw.riskLevel === "critical") risk_level = "Critical";
  if (raw.risk_level === "high" || raw.riskLevel === "high") risk_level = "High";
  if (raw.risk_level === "medium" || raw.riskLevel === "medium") risk_level = "Medium";
  if (raw.risk_level === "low" || raw.riskLevel === "low") risk_level = "Low";

  let operational_status: PipelineAsset["operational_status"] = raw.operational_status || "Active";
  if (raw.operationalStatus === "normal") operational_status = "Active";
  if (raw.operationalStatus === "warning") operational_status = "Maintenance Required";
  if (raw.operationalStatus === "critical") operational_status = "Under Repair";
  if (raw.operationalStatus === "maintenance") operational_status = "Inactive";

  let inspection_status: PipelineAsset["inspection_status"] = raw.inspection_status || "Passed";
  if (raw.inspectionStatus === "passed" || raw.inspectionStatus === "not_required") inspection_status = "Passed";
  if (raw.inspectionStatus === "inspection_required") inspection_status = "Scheduled";
  if (raw.inspectionStatus === "under_review") inspection_status = "Pending Review";
  if (raw.inspectionStatus === "failed") inspection_status = "Failed - Action Required";

  return {
    id,
    pipe_id,
    location,
    zone,
    latitude,
    longitude,
    installation_year,
    pipe_age,
    material,
    diameter_mm,
    length_m,
    max_capacity_lps,
    pressure_bar,
    flow_rate_lps,
    temperature_c,
    operational_status,
    inspection_status,
    risk_score,
    risk_level,
    last_inspection_date: raw.last_inspection_date || raw.lastInspectionDate || "2026-06-01",
    installationYear: installation_year,
    age: pipe_age,
    diameterMm: diameter_mm,
    lengthM: length_m,
    capacity: max_capacity_lps,
    pressureBar: pressure_bar,
    flowRate: flow_rate_lps,
    temperatureC: temperature_c,
    operationalStatus: raw.operationalStatus || (risk_level === "Critical" ? "critical" : risk_level === "High" || risk_level === "Medium" ? "warning" : "normal"),
    inspectionStatus: raw.inspectionStatus || "not_required",
    riskScore: risk_score,
    lastInspectionDate: raw.last_inspection_date || raw.lastInspectionDate || "2026-06-01"
  };
}

export function getPipelineStats(assets: PipelineAsset[] = PIPELINE_ASSETS_50) {
  const total = assets.length;
  const normal = assets.filter((a) => a.risk_level === "Low").length;
  const warning = assets.filter((a) => a.risk_level === "Medium" || a.risk_level === "High").length;
  const critical = assets.filter((a) => a.risk_level === "Critical").length;
  const maintenance = assets.filter(
    (a) => a.operational_status === "Maintenance Required" || a.operational_status === "Under Repair" || a.operational_status === "Inactive"
  ).length;

  const avgPressure = Number((assets.reduce((acc, a) => acc + a.pressure_bar, 0) / (total || 1)).toFixed(2));
  const avgFlow = Number((assets.reduce((acc, a) => acc + a.flow_rate_lps, 0) / (total || 1)).toFixed(1));
  const avgAge = Math.round(assets.reduce((acc, a) => acc + a.pipe_age, 0) / (total || 1));
  const avgRisk = Math.round(assets.reduce((acc, a) => acc + a.risk_score, 0) / (total || 1));

  return {
    total,
    normal,
    warning,
    critical,
    maintenance,
    avgPressure,
    avgFlow,
    avgAge,
    avgRisk
  };
}

export function convertToCSV(assets: PipelineAsset[]): string {
  const headers = [
    "id",
    "pipe_id",
    "location",
    "zone",
    "latitude",
    "longitude",
    "installation_year",
    "pipe_age",
    "material",
    "diameter_mm",
    "length_m",
    "max_capacity_lps",
    "pressure_bar",
    "flow_rate_lps",
    "temperature_c",
    "operational_status",
    "inspection_status",
    "risk_score",
    "risk_level",
    "last_inspection_date"
  ];

  const rows = assets.map((a) => [
    `"${a.id}"`,
    `"${a.pipe_id}"`,
    `"${a.location}"`,
    `"${a.zone}"`,
    a.latitude,
    a.longitude,
    a.installation_year,
    a.pipe_age,
    `"${a.material}"`,
    a.diameter_mm,
    a.length_m,
    a.max_capacity_lps,
    a.pressure_bar,
    a.flow_rate_lps,
    a.temperature_c,
    `"${a.operational_status}"`,
    `"${a.inspection_status}"`,
    a.risk_score,
    `"${a.risk_level}"`,
    `"${a.last_inspection_date}"`
  ]);

  return [headers.join(","), ...rows.map((r) => r.join(","))].join("\n");
}

export type NormalizationResult = {
  records: PipelineAsset[];
  rejectedCount: number;
  errors: Array<{
    index: number;
    message: string;
  }>;
};

export function normalizePipelineAssets(raw: unknown): NormalizationResult {
  if (!Array.isArray(raw)) {
    return {
      records: [],
      rejectedCount: 0,
      errors: [{ index: -1, message: "Expected raw input to be an array" }]
    };
  }

  const records: PipelineAsset[] = [];
  const errors: Array<{ index: number; message: string }> = [];

  raw.forEach((item, index) => {
    try {
      const normalized = adapterToNormalizedPipelineAsset(item);
      const parsed = PipelineAssetSchema.parse(normalized);
      records.push(parsed);
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      errors.push({ index, message });
    }
  });

  return {
    records,
    rejectedCount: errors.length,
    errors
  };
}

export async function loadPipelineAssets(signal?: AbortSignal): Promise<{
  records: PipelineAsset[];
  rejectedCount: number;
  source: string;
}> {
  try {
    const res = await fetch("/data/pipelines.json", { signal });
    if (!res.ok) {
      throw new Error(`HTTP error ${res.status}`);
    }
    const data = await res.json();
    const normalized = normalizePipelineAssets(data);
    if (normalized.records.length === 0) {
      throw new Error("No valid records accepted from /data/pipelines.json");
    }
    return {
      records: normalized.records,
      rejectedCount: normalized.rejectedCount,
      source: "client-fetch"
    };
  } catch {
    const fallbackNormalized = normalizePipelineAssets(PIPELINE_ASSETS_50);
    return {
      records: fallbackNormalized.records,
      rejectedCount: fallbackNormalized.rejectedCount,
      source: "static-fallback"
    };
  }
}

